Repository w3c/ttml2, pull requests merged in 2018-07, with the labels that each got.

#865 Remove parenthetical reference to use value (#861).
  spec/ttml2.xml
Labels: editorial, pending merge

#871 Clarify inheritance of 'normal' line height with further resolved com…
  spec/ttml2.xml
Labels: editorial, pending merge

#873 Add missing tts:unicodeBidi 'isolate' value to schemas (#872).
  spec/rnc/ttml2-datatypes.rnc
  spec/xsd/ttml2-datatypes.xsd
Labels: editorial, pending merge

#875 Add tts:display 'inlineBlock' value to schemas; update rnc schemas to…
  spec/rnc/ttml2-animation.rnc
  spec/rnc/ttml2-audio-attribs.rnc
  spec/rnc/ttml2-classes.rnc
  spec/rnc/ttml2-content.rnc
  spec/rnc/ttml2-core-attribs.rnc
  spec/rnc/ttml2-datatypes.rnc
  spec/rnc/ttml2-document.rnc
  spec/rnc/ttml2-embedded.rnc
  spec/rnc/ttml2-head.rnc
  spec/rnc/ttml2-isd.rnc
  spec/rnc/ttml2-layout.rnc
  spec/rnc/ttml2-metadata-attribs.rnc
  spec/rnc/ttml2-metadata-items.rnc
  spec/rnc/ttml2-metadata.rnc
  spec/rnc/ttml2-parameter-attribs.rnc
  spec/rnc/ttml2-parameter-items.rnc
  spec/rnc/ttml2-parameters.rnc
  spec/rnc/ttml2-styling-attribs.rnc
  spec/rnc/ttml2-styling.rnc
  spec/rnc/ttml2-timing-attribs.rnc
  spec/rnc/ttml2.rnc
  spec/xsd/ttml2-datatypes.xsd
Labels: editorial, pending merge

#880 Clarify 'any attribute' language (#879).
  spec/ttml2.xml
Labels: editorial

#885 Remove @style from initial in schemas (#878).
  spec/rnc/ttml2-layout.rnc
  spec/rnc/ttml2-styling-attribs.rnc
  spec/rnc/ttml2-styling.rnc
  spec/xsd/ttml2-styling.xsd
Labels: editorial, pending approval

#915 Switch to CR entities, update dates in status.
  spec/entities.dtd
  spec/entitiescr.dtd
  spec/status.xml
  spec/ttml2.xml
Labels: no spec change

#902 Update acknowledgments (#901).
  spec/acknowledgements-current.txt
  spec/ttml2.xml
Labels: editorial, pending merge

#897 Add clip{Begin,End} attributes to tt:audio in schemas (#887).
  spec/rnc/ttml2-embedded.rnc
  spec/xsd/ttml2-embedded.xsd
Labels: editorial, pending merge

#898 Ensure audio and image (in presentation contexts) are treated as cont…
  spec/ttml2.xml
Labels: pending merge, substantive

#908 Fix typos and styling (#894).
  spec/ttml2.xml
Labels: editorial, pending merge

#912 Note that ISD construction may include early style resolution (#904).
  spec/ttml2.xml
Labels: editorial, pending merge

#913 Update TTML1 reference (#884).
  spec/ttml2.xml
Labels: pending merge, substantive

#914 Scale back style animatability (#881).
  spec/ttml2.xml
Labels: pending merge, substantive

#867 Clarify constancy of ECP and EPP (#860).
  spec/ttml2.xml
Labels: pending merge, substantive

#920 Add @extent to isd:{sequence,isd} (#919).
  spec/rnc/ttml2-isd.rnc
  spec/ttml2.xml
  spec/xsd/ttml2-datatypes.xsd
  spec/xsd/ttml2-isd.xsd
Labels: pending merge, substantive

#921 Allow continuous animation of border color (#917).
  spec/ttml2.xml
Labels: pending merge, substantive

#924 Address possible conflict in placement of ruby text containers (#882).
  spec/ttml2.xml
Labels: pending merge, substantive

#886 Note potential for false negatives with [validate document] (#876).
  spec/ttml2.xml
Labels: editorial

#900 Improve definition of conditionally excluded (included) (#893).
  spec/ttml2.xml
Labels: editorial, pending approval, pending re-review

#911 Editorial improvements to 11.3.1.2 Inline Regions (#903).
  spec/ttml2.xml
Labels: editorial, pending merge

#922 Sort order of elements in list in 10.4.4.4 (#916).
  spec/ttml2.xml
Labels: editorial, pending approval

#925 Improve structure, handle image in [flow transformation], and link pr…
  spec/ttml2.xml
Labels: pending merge, substantive

#890 Clarify use of terms altitude, depth, and line gap; add non-normative…
  spec/ttml2.xml
  spec/xmlspec-ttml2.dtd
Labels: editorial, pending merge

#909 Clarify computed cell size; improve language pertaining to pixels (#8…
  spec/ttml2.xml
Labels: editorial, pending approval

#928 Clarify that descendants of conditionally excluded elements are alway…
  spec/ttml2.xml
Labels: editorial

#930 Map out-of-line animation to inline animation to handle styling seman…
  spec/ttml2.xml
Labels: pending approval, substantive

#934 Fix typos (#932).
  spec/ttml2.xml
Labels: editorial, pending approval

#936 Fix link warning for DVBSS bibliographic entry (#935).
  spec/ttml2.xml
Labels: editorial, pending approval
