Repository w3c/ttml2, pull requests merged in 2018-02, with the labels that each got.

#644 Fix link to ED in README (#641).
  README.md
Labels: no change

#645 Fix typo "steroscopic" (#640).
  spec/ttml2.xml
Labels: editorial

#646 Fixing missing 9 in digit definitions (#642).
  spec/ttml2.xml
Labels: editorial

#593 Map measure 'auto' on region to '100%' rather than 'available' (#351).
  spec/ttml2.xml
Labels: substantive

#622 Add better overflow example (#358).
  spec/build.xml
  spec/examples/ex4-overflow.xml
  spec/images/overflow.png
  spec/ttml2.xml
Labels: editorial

#648 Update to 2018 Process document (#631).
  spec/status.xml
Labels: editorial

#595 Remove support for unitless lengths (#561).
  spec/ttml2.xml
Labels: substantive

#606 Remove ttp:version parameter attribute (#435).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/rnc/ttml2-datatypes.rnc
  spec/rnc/ttml2-parameter-attribs.rnc
  spec/ttml2-changes.html
  spec/ttml2.xml
  spec/xsd/ttml2-datatypes.xsd
  spec/xsd/ttml2-parameter-attribs.xsd
Labels: substantive

#596 Remove root style inheritance (#546).
  spec/rnc/ttml2-document.rnc
  spec/ttml2-changes.html
  spec/ttml2.xml
  spec/xsd/ttml2-document.xsd
Labels: substantive

#597 Remove @format attribute from audio, font, and image elements (#544).
  spec/rnc/ttml2-embedded.rnc
  spec/ttml2.xml
  spec/xsd/ttml2-embedded.xsd
Labels: substantive

#637 Mark text orientation sideways{Left,Right} at risk (#280).
  spec/status.xml
Labels: editorial

#599 Forward interoperability of attribute extensions in TT namespaces (#358).
  spec/ttml2.xml
Labels: substantive

#604 Remove auto value for rubyAlign (#249).
  spec/rnc/ttml2-datatypes.rnc
  spec/ttml2.xml
  spec/xsd/ttml2-datatypes.xsd
Labels: substantive

#608 Improve animation value syntax (#383).
  spec/ttml2.xml
Labels: substantive

#614 Further constrain ruby descendants (#372).
  spec/ttml2.xml
Labels: substantive

#598 New feature designators for extent (#582).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: substantive

#653 Review ISD construction vs syntax (#376).
  spec/ttml2.xml
Labels: editorial, pending review

#654 Remove issue note that has already been addressed (#358).
  spec/ttml2.xml
Labels: editorial

#605 Add note for wide ruby annotations (#250).
  spec/ttml2.xml
Labels: agenda

#613 Adding ruby pinyin example (#251, #274).
  spec/images/ruby-pinyin.png
  spec/ttml2.xml
Labels: pending review

#617 Enable inline ruby presentation based on document processing context (#255).
  spec/ttml2.xml
Labels: pending review

#618 Use mono ruby in example of rubyPosition (#275).
  spec/ttml2.xml
Labels: pending review

#619 Clarify use of tts:textCombine (#278).
  spec/ttml2.xml
Labels: editorial

#620 Clarify presentation processor behaviour for anamorphic fonts
  spec/ttml2.xml
Labels: editorial

#623 Mapping between ruby base and ruby text in complex cases (#247).
  spec/ttml2.xml
Labels: editorial

#624 Remove tts:rubyOffset (#252).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/rnc/ttml2-datatypes.rnc
  spec/rnc/ttml2-styling-attribs.rnc
  spec/ttml2-changes.html
  spec/ttml2.xml
  spec/xsd/ttml2-datatypes.xsd
  spec/xsd/ttml2-styling-attribs.xsd
Labels: substantive

#625 Use glyph area wording for textOrientation (#281).
  spec/ttml2.xml
Labels: editorial

#632 Fill in definition of tts:fontSelectionStrategy, add to schema, fix t…
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/rnc/ttml2-datatypes.rnc
  spec/rnc/ttml2-styling-attribs.rnc
  spec/status.xml
  spec/ttml2.xml
  spec/xsd/ttml2-datatypes.xsd
  spec/xsd/ttml2-styling-attribs.xsd
Labels: substantive

#667 Add CR exit criteria
  spec/entities.dtd
  spec/entitiescr.dtd
  spec/status.xml
  spec/ttml2.xml
Labels: editorial

#638 Simplify syntax of animation value used with set element (#633).
  spec/ttml2.xml
Labels: substantive

#649 Specify semantics of percentage length used with tts:{bpd,ipd} (#369).
  spec/ttml2.xml
Labels: pending review, substantive

#647 Deprecate use of sequential time containment with smpte discontinuous…
  spec/ttml2.xml
Labels: substantive

#664 Add missing feature designators (#657).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: pending review, substantive

#616 Make begin times relative to the document temporal coordinate space (#512)
  spec/ttml2.xml
Labels: substantive

#594 Specify missing validation semantics (#362, #363, #367, #541).
  spec/ttml2-changes.html
  spec/ttml2.xml
Labels: substantive

#603 Introduce anonymous span creation procedure (#358).
  spec/ttml2.xml
Labels: member plans to object to CR1 if not resolved, substantive

#639 Add #set* feature designators, expand/refactor #animate* and #animati…
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: member plans to object to CR1 if not resolved, substantive

#669 Add at-risk features (#662).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/status.xml
  spec/ttml2.xml
Labels: editorial, pending review

#670 Comment out editor and issue notes for CR1 (#660).
  spec/ttml2.xml
Labels: editorial

#671 Update description of vocabulary additions (#658).
  spec/ttml2-changes.html
  spec/ttml2.xml
Labels: editorial

#677 Add missing at-risk feature to SoTD as resolved (#676).
  spec/status.xml
Labels: editorial, pending review
