Repository w3c/ttml2, pull requests merged in 2018-06, with the labels that each got.

#774 Make tts:ruby non-animatable (#773).
  spec/ttml2.xml
Labels: substantive

#805 Add and update element derivations (#380).
  spec/ttml2.xml
Labels: editorial

#803 Collapse language for style application to paragraph text nodes; add …
  spec/ttml2.xml
Labels: editorial

#740 Clarify application of ruby alignment and positioning (#717).
  spec/ttml2.xml
Labels: substantive

#755 Describe generically compliant processors that support only external …
  spec/ttml2.xml
Labels: editorial

#731 Refactor semantics of #region-inline-implicit (#727).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: substantive

#794 Clean up and refactor features (#688, #763, #789, #790, #791, #792, #…
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: pending re-review, substantive

#742 Exclude implied animation of region via tts:origin on div and p (#710).
  spec/ttml2.xml
Labels: editorial, pending merge

#772 Add explicit exceptions to ignoring element semantics with condition …
  spec/ttml2.xml
Labels: pending merge, substantive

#665 Clarify that metadata has no presentation semantics (#656).
  spec/ttml2.xml
Labels: substantive

#769 Exclude vertical length offset as 1st component in 2 component positi…
  spec/ttml2.xml
Labels: pending re-review, substantive

#651 Update requirements for claim of document (content) compliance (#495).
  spec/ttml2.xml
Labels: pending merge, substantive

#652 Resolve confusion between default and implicit (#590).
  spec/ttml2.xml
Labels: editorial, pending merge

#798 Clarify 'outside' for annotation position (#782)
  spec/ttml2.xml
Labels: pending merge, substantive

#799 Clarify use of font* properties in resolving default line height (#785).
  spec/ttml2.xml
Labels: pending merge, substantive

#807 Add tts:lineShear and tts:shear style attributes (#784).
  spec/images/lineShear_1.png
  spec/images/shear_1.png
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/rnc/ttml2-datatypes.rnc
  spec/rnc/ttml2-styling-attribs.rnc
  spec/status.xml
  spec/ttml2.xml
  spec/xsd/ttml2-datatypes.xsd
  spec/xsd/ttml2-styling-attribs.xsd
Labels: pending merge, substantive

#808 Add xml:base to core vocabulary (#804).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/rnc/ttml2-core-attribs.rnc
  spec/rnc/ttml2-embedded.rnc
  spec/rnc/ttml2-isd.rnc
  spec/ttml2.xml
  spec/xsd/ttml2-core-attribs.xsd
  spec/xsd/ttml2-isd.xsd
  spec/xsd/ttml2-parameter-items.xsd
Labels: pending merge, substantive

#810 Clarify luminanceGain applicability.
  spec/ttml2.xml
Labels: pending merge, substantive

#812 Remove around and between in rubyReserve (#811).
  spec/images/rubyReserve1.png
  spec/images/rubyReserve2.png
  spec/images/rubyReserve3.png
  spec/images/rubyReserve4.png
  spec/images/rubyReserve5.png
  spec/images/rubyReserve6.png
  spec/images/rubyReserve_2A_auto.png
  spec/images/rubyReserve_2B_auto.png
  spec/images/rubyReserve_7A_around.png
  spec/images/rubyReserve_7B_around.png
  spec/images/rubyReserve_8A_between.png
  spec/images/rubyReserve_8B_between.png
  spec/ttml2.xml
Labels: pending merge, substantive

#770 Add features for standard PNG images (#694).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: discussed and agreed, substantive

#818 Remove digits keyword from tts:textCombine (#817).
  spec/images/textCombine_final.png
  spec/rnc/ttml2-datatypes.rnc
  spec/ttml2.xml
  spec/xsd/ttml2-datatypes.xsd
Labels: pending approval, substantive

#705 Improve constraint/clarification semantics for animate element (#700).
  spec/ttml2.xml
  spec/xsd/ttml2-datatypes.xsd
Labels: pending approval, substantive

#826 Change semantics of <length> component of tts:rubyReserve (#779).
  spec/ttml2.xml
Labels: pending approval, substantive

#824 Remove word 'measure' that does not refer to <measure> value syntax (…
  spec/ttml2.xml
Labels: editorial, pending approval

#815 Further refinement of features (#814).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/rnc/ttml2-datatypes.rnc
  spec/ttml2.xml
  spec/xsd/ttml2-datatypes.xsd
Labels: pending approval, substantive

#828 Fix typo in rubyReserve.
  spec/ttml2.xml
Labels: editorial

#825 Add informative text clarifying line height and line stacking semanti…
  spec/ttml2.xml
  spec/xmlspec-ttml2.dtd
  spec/xmlspec-ttml2.xsl
Labels: editorial, pending approval

#833 Improve constraints on 'tts:rubyPosition' usage (#832).
  spec/ttml2.xml
Labels: substantive

#836 Update requirements appendix M
  spec/ttml2.xml
Labels: editorial, pending merge

#843 Refactor #textEmphasis* features to avoid negative definitions (#838,…
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: pending merge, substantive

#844 Add #xlink feature (#840).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: pending merge, substantive

#845 Add #visibility-image, #visibility-version-2; clarify equivalence for…
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: pending merge, substantive

#848 Add `#region-implied-animation` to the at risk list.
  spec/status.xml
Labels: editorial

#851 Clarify that height term can mean horizontal axis in exceptional case…
  spec/ttml2.xml
Labels: editorial, pending approval

#852 Clarify semantics of implied inline animation of the same style on re…
  spec/ttml2.xml
Labels: editorial, pending approval

#850 Refactor #base* features (#834).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: pending approval, substantive

#849 Do not extend #extent-length in defining #extent-measure (#846).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: pending approval, substantive

#854 Add #extent-length-version-2 feature (#853).
  spec/profiles/ttml2-full.xml
  spec/profiles/ttml2-presentation.xml
  spec/profiles/ttml2-transformation.xml
  spec/ttml2.xml
Labels: pending merge, substantive

#831 Tweak dates, fix figure numbering, update changes document.
  spec/acknowledgements.xml
  spec/entitiescr.dtd
  spec/status.xml
  spec/ttml2-changes.html
  spec/ttml2-errata.html
  spec/ttml2.xml
Labels: editorial, pending merge

#855 Fix permanent link redirects.
  spec/ttml2.xml
Labels: editorial

#864 Add audio features to at risk list (#863).
  spec/status.xml
Labels: editorial, pending approval

#869 Revert to Editor's Draft (ED); update to PR type (#868).
  spec/entities.dtd
  spec/entitiesedcopy.dtd
Labels: no spec change, pending approval
